services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: msgerencial
      POSTGRES_PASSWORD: msgerencial
      POSTGRES_DB: msgerencial
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
